version: '3.9'
 
services:

  db:
    image: postgres:13-alpine
    env_file:
      - ./.env.prod
    container_name: "postgres"
    ports:
      - "5432:5432"

  app:
    build:
      context: .
    ports:
      - "8000:8000"
    volumes:
      - static:/static
    command: >
      sh -c "python manage.py makemigrations &&
             python manage.py migrate &&
             gunicorn config.wsgi:application --bind 0.0.0.0:8000"
    env_file:
      - ./.env.prod
    container_name: "django"
    depends_on:
      - db
  
  nginx:
    build: ./nginx
    volumes:
      - static:/static
    ports: 
      - "80:80"
    container_name: "nginx"
    depends_on: 
      - app
  
  redis:
    image: redis:alpine
    container_name: "redis"

  celery:
    restart: always
    build:
      context: .
    command: celery -A config worker --loglevel=INFO
    volumes:
      - .:/usr/src/app
    env_file:
      - ./.env.prod
    container_name: "celery"
    depends_on:
      - db
      - redis
      - app

volumes:
  static:
