version: '3.9'
 
services:

  postgres:
    container_name: "postgres"
    image: postgres:13-alpine
    volumes: 
      - postgres_data:/var/lib/postgresql/data
    env_file:
      - ./.env.prod
    ports:
      - 5432:5432

  django:
    container_name: "django"
    build:
      context: .
      dockerfile: ./docker/prod/django/Dockerfile
    ports:
      - 8000:8000
    volumes:
      - .:/usr/src/app
    env_file:
      - ./.env.prod
    image: django-image
    depends_on:
      - postgres
  
  redis:
    container_name: "redis"
    image: redis:alpine

volumes: 
  postgres_data:
