version: '3.9'
 
services:

  postgres:
    container_name: "postgres"
    image: postgres:13-alpine
    volumes: 
      - postgres_data:/var/lib/postgresql/data
    env_file:
      - ./.env.dev
    ports:
      - 5432:5432

  django:
    container_name: "django"
    build: 
      context: .
      dockerfile: ./docker/dev/django/Dockerfile
    command: >
      sh -c "python manage.py migrate &&
             python manage.py createsuperuser --no-input &&
             python manage.py runserver 0.0.0.0:8000"
    ports:
      - 8000:8000
    volumes:
      - .:/usr/src/app
    env_file:
      - ./.env.dev
    image: django-image
    depends_on:
      - postgres
      - redis
  
  redis:
    container_name: "redis"
    image: redis:alpine

  celery:
    container_name: "celery"
    restart: always
    build: 
      context: .
      dockerfile: ./docker/dev/django/Dockerfile
    command: celery -A config worker --loglevel=INFO
    volumes:
      - .:/usr/src/app
    env_file:
      - ./.env.dev
    depends_on:
      - django
      - redis

volumes: 
  postgres_data:
