version: '3.9'
 
services:

  db:
    image: postgres:13-alpine
    env_file:
      - ./.env.dev
    container_name: "postgres"
    ports:
      - "5432:5432"

  app:
    build:
      context: .
    ports:
      - "8000:8000"
    volumes:
      - .:/usr/src/app
    command: >
      sh -c "python manage.py makemigrations &&
             python manage.py migrate &&
             python manage.py runserver 0.0.0.0:8000"
    env_file:
      - ./.env.dev
    container_name: "django"
    depends_on:
      - db
  
  redis:
    image: redis:alpine
    container_name: "redis"

  celery:
    restart: always
    build:
      context: .
    command: celery -A config worker --loglevel=INFO
    volumes:
      - .:/usr/src/app
    env_file:
      - ./.env.dev
    container_name: "celery"
    depends_on:
      - db
      - redis
      - app
  