version: '3.9'
 
services:

  postgres:
    container_name: "postgres"
    restart: always
    build: 
      context: .
      dockerfile: ./docker/prod/postgres/Dockerfile
    env_file:
      - ./.env.prod
    ports:
      - 5432:5432

  django:
    container_name: "django"
    restart: always
    build: 
      context: .
      dockerfile: ./docker/prod/django/Dockerfile
    command: >
      sh -c "python manage.py migrate &&
             gunicorn -w 5 config.wsgi -b 0.0.0.0:8000"
    ports:
      - 8000:8000
    volumes:
      - .:/usr/src/app
      - ./static:/static
      - ./media:/media
    env_file:
      - ./.env.prod
    depends_on:
      - postgres
      - redis
  
  redis:
    container_name: "redis"
    restart: always
    image: redis:alpine

  celery:
    container_name: "celery"
    restart: always
    build: 
      context: .
      dockerfile: ./docker/prod/django/Dockerfile
    command: celery -A config worker --loglevel=INFO
    volumes:
      - .:/usr/src/app
    env_file:
      - ./.env.prod
    depends_on:
      - django
      - redis
  
  nginx:
    container_name: "nginx"
    restart: always
    build:
      context: .
      dockerfile: ./docker/prod/nginx/Dockerfile
    volumes: 
      - ./static:/static
      - ./media:/media
    ports: 
      - 80:80
    depends_on: 
      - django

volumes: 
  postgres_data:
  static:
  media:
