version: '3.9'
 
services:

  postgres:
    container_name: "postgres"
    restart: always
    build: 
      context: .
      dockerfile: ./docker/prod/postgres/Dockerfile
    volumes: 
      - postgres_data:/var/lib/postgresql/data
    env_file:
      - .env.prod
    ports:
      - 5432:5432

  django:
    container_name: "django"
    restart: always
    build: 
      context: .
      dockerfile: ./docker/prod/django/Dockerfile
    command: >
      sh -c "python manage.py migrate &&
             gunicorn -w 5 config.wsgi -b 0.0.0.0:8000"
    expose: 
      - 8000
    volumes:
      - .:/usr/src/app
      - ./static:/static
      - ./media:/media
    env_file:
      - .env.prod
    depends_on:
      - postgres
      - redis
  
  redis:
    container_name: "redis"
    restart: always
    image: redis:alpine

  celery:
    container_name: "celery"
    restart: always
    build: 
      context: .
      dockerfile: ./docker/prod/django/Dockerfile
    command: celery -A config worker --loglevel=INFO
    volumes:
      - .:/usr/src/app
    env_file:
      - .env.prod
    depends_on:
      - django
      - redis
  
  nginx:
    container_name: "nginx"
    restart: always
    build:
      context: .
      dockerfile: ./docker/prod/nginx/Dockerfile
    volumes: 
      - ./static:/static
      - ./media:/media
      - certs:/etc/nginx/certs
      - html:/usr/share/nginx/html
      - vhost:/etc/nginx/vhost.d
      - /var/run/docker.sock:/tmp/docker.sock:ro
    labels:
      - "com.github.jrcs.letsencrypt_nginx_proxy_companion.nginx_proxy"
    ports: 
      - 80:80
      - 443:443
    depends_on: 
      - django

  docker-gen:
    image: jwilder/docker-gen
    command: -notify-sighup nginx-proxy -watch /etc/docker-gen/templates/nginx.tmpl /etc/nginx/conf.d/default.conf
    container_name: nginx-proxy-gen
    depends_on:
      - nginx
    volumes:
      - conf:/etc/nginx/conf.d
      - vhost:/etc/nginx/vhost.d
      - certs:/etc/nginx/certs:ro
      - ./nginx.tmpl:/etc/docker-gen/templates/nginx.tmpl:ro
      - /var/run/docker.sock:/tmp/docker.sock:ro
    labels:
      - "com.github.jrcs.letsencrypt_nginx_proxy_companion.docker_gen"
    restart: always
    
  nginx_ssl:
    container_name: "nginx_ssl"
    image: jrcs/letsencrypt-nginx-proxy-companion
    env_file: 
      - .env.prod
    volumes: 
      - certs:/etc/nginx/certs
      - html:/usr/share/nginx/html
      - vhost:/etc/nginx/vhost.d
      - /var/run/docker.sock:/var/run/docker.sock:ro
    depends_on: 
      - nginx
      - docker-gen

volumes: 
  postgres_data:
  static:
  media:
  certs:
  html:
  vhost:

networks:
  default:
    external:
      name: nginx
