# Generated by Django 3.2.3 on 2021-05-16 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='media',
            name='type',
            field=models.CharField(choices=[('edited_image', 'Edited Img'), ('unedited_image', 'Unedited Img'), ('edited_video', 'Edited Video'), ('unedited_video', 'Unedited Video'), ('template_video', 'Template Video'), ('gif', 'Gif')], default='unedited_image', max_length=16),
        ),
    ]
