# Generated by Django 3.2.3 on 2021-05-30 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_alter_media_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='media',
            name='preview',
            field=models.CharField(blank=True, max_length=2048, null=True),
        ),
        migrations.AlterField(
            model_name='media',
            name='type',
            field=models.CharField(choices=[('edited_image', 'Edited Img'), ('unedited_image', 'Unedited Img'), ('edited_video', 'Edited Video'), ('unedited_video', 'Unedited Video'), ('edited_gif', 'Edited Gif'), ('unedited_gif', 'Unedited Gif')], max_length=16),
        ),
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.CharField(blank=True, choices=[('new', 'New'), ('processing', 'Processing'), ('done', 'Done'), ('error', 'Error')], default='new', max_length=32),
        ),
    ]
