# Generated by Django 3.2.3 on 2021-05-30 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0003_auto_20210530_1801'),
    ]

    operations = [
        migrations.AlterField(
            model_name='media',
            name='type',
            field=models.CharField(choices=[('edited_image', 'Edited Img'), ('unedited_image', 'Unedited Img'), ('edited_video', 'Edited Video'), ('unedited_video', 'Unedited Video'), ('edited_gif', 'Edited Gif'), ('unedited_gif', 'Unedited Gif'), ('template_gif', 'Template Gif'), ('template_video', 'Template Vid')], max_length=16),
        ),
    ]
