# Generated by Django 3.2.3 on 2021-06-11 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0005_alter_media_preview'),
    ]

    operations = [
        migrations.CreateModel(
            name='Config',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('dev', 'Dev'), ('prod', 'Prod')], max_length=8)),
                ('lock_app_after_function', models.BooleanField()),
                ('lock_app_before_function', models.BooleanField()),
                ('lock_main_menu', models.BooleanField()),
                ('amount_try_function', models.PositiveSmallIntegerField(default=1)),
            ],
        ),
    ]
