# Generated by Django 3.2.3 on 2021-06-16 15:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0006_config'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appfunction',
            name='name',
            field=models.CharField(max_length=32, unique=True, verbose_name='function'),
        ),
        migrations.AlterField(
            model_name='subfunction',
            name='name',
            field=models.CharField(max_length=32, unique=True, verbose_name='subfunction'),
        ),
        migrations.AlterField(
            model_name='task',
            name='bot',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tasks.bot', verbose_name='bot'),
        ),
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.CharField(blank=True, choices=[('new', 'New'), ('processing', 'Processing'), ('done', 'Done'), ('error', 'Error'), ('canceled', 'Canceled')], default='new', max_length=32),
        ),
    ]
