# Generated by Django 3.2.3 on 2021-05-15 09:13

from django.db import migrations, models
import django.db.models.deletion
import taggit.managers


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('taggit', '0003_taggeditem_add_unique_index'),
    ]

    operations = [
        migrations.CreateModel(
            name='App',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32, unique=True)),
            ],
            options={
                'db_table': 'app',
            },
        ),
        migrations.CreateModel(
            name='AppFunction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32, unique=True)),
                ('app', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tasks.app')),
            ],
            options={
                'db_table': 'app_function',
            },
        ),
        migrations.CreateModel(
            name='Bot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32, unique=True)),
                ('state', models.CharField(choices=[('enabled', 'Enabled'), ('disabled', 'Disabled')], default='disabled', max_length=8)),
            ],
            options={
                'db_table': 'bot',
            },
        ),
        migrations.CreateModel(
            name='Media',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('media', models.FileField(upload_to='tasks')),
                ('state', models.CharField(choices=[('edited', 'Edited'), ('unedited', 'Unedited'), ('template', 'Template')], default='unedited', max_length=8)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('tags', taggit.managers.TaggableManager(help_text='A comma-separated list of tags.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Tags')),
            ],
            options={
                'verbose_name_plural': 'media',
                'db_table': 'media',
            },
        ),
        migrations.CreateModel(
            name='Subfunction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32, unique=True)),
                ('function', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='tasks.appfunction')),
            ],
            options={
                'db_table': 'subfunction',
            },
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(blank=True, choices=[('new', 'New'), ('processing', 'Processing'), ('done', 'Done')], default='new', max_length=32)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('bot', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tasks.bot')),
                ('function', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tasks.appfunction', verbose_name='function')),
                ('media', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tasks.media')),
                ('subfunction', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tasks.subfunction', verbose_name='subfunction')),
            ],
            options={
                'db_table': 'task',
            },
        ),
    ]
