# Generated by Django 3.2.3 on 2021-05-13 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_auto_20210513_1523'),
    ]

    operations = [
        migrations.AddField(
            model_name='media',
            name='tags',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
    ]
