# Generated by Django 3.2.3 on 2021-05-16 05:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_alter_media_tags'),
    ]

    operations = [
        migrations.AlterField(
            model_name='media',
            name='state',
            field=models.CharField(choices=[('edited', 'Edited'), ('unedited', 'Unedited'), ('template', 'Template'), ('template_image', 'Template Image')], default='unedited', max_length=16),
        ),
        migrations.RemoveField(
            model_name='task',
            name='media',
        ),
        migrations.AddField(
            model_name='task',
            name='media',
            field=models.ManyToManyField(to='tasks.Media'),
        ),
    ]
