# Generated by Django 3.2.3 on 2021-05-15 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0003_media_tags'),
    ]

    operations = [
        migrations.AlterField(
            model_name='media',
            name='state',
            field=models.CharField(choices=[('edited', 'Edited'), ('unedited', 'Unedited'), ('template', 'Template')], default='unedited', max_length=8),
        ),
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.CharField(blank=True, choices=[('new', 'New'), ('processing', 'Processing'), ('done', 'Done')], default='new', max_length=32),
        ),
    ]
