# Generated by Django 3.2.3 on 2021-05-30 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0004_alter_media_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='media',
            name='preview',
            field=models.URLField(blank=True, max_length=2048, null=True),
        ),
    ]
